#!/bin/bash
#SBATCH --job-name=demo3-dds
#SBATCH --account=nn4605k
#SBATCH --time=15:00:00
#SBATCH --mem-per-cpu=15G --partition=bigmem 
# Number of cores:
#SBATCH --cpus-per-task=20

#set up job enviroment
#source /etc/profile.d/modules.csh
#source /cluster/bin/jobsetup
#module use --append /cluster/etc/modulefiles
#module load java/jdk1.7.0_80
#module unload Java/1.8.0_212
#module purge
#module --ignore-cache load Java/1.7.0_80

#the last two examples are for dds_analysis
./run_rat_part2_test.sh
./run_rat_part3_test.sh

